%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{defproblem}{Linq-MultipleEnumeration}
\begin{onlyproblem}
  Что выведет следующий код?
  \begin{source}
  public static int CreateNumber(int x)
  {
    Console.WriteLine("CreateNumber: " + x);
    return x;
  }
  public static IEnumerable<int> GetSmallNumbers()
  {    
    yield return CreateNumber(1);
    yield return CreateNumber(2);
  }
  public static int[] GetArray()
  {
    var numbers = GetSmallNumbers();
    foreach (var number in numbers)
      Console.WriteLine("GetArray:" + number);
    return numbers.ToArray();
  }
  void Main()
  {
    GetArray();
  }
  \end{source}
\end{onlyproblem}
\begin{onlysolution}
  \begin{source}
  CreateNumber: 1
  GetArray:1
  CreateNumber: 2
  GetArray:2
  CreateNumber: 1
  CreateNumber: 2
  \end{source}
\end{onlysolution}
\end{defproblem}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{defproblem}{Linq-LifeAfterYield}
\begin{onlyproblem}
  Что выведет следующий код?
  \begin{source}
  public IEnumerable<int> Foo()
  {
    yield return 1;
    Console.WriteLine("Foo");
  }
  void Main()
  {
    foreach (var i in Foo())
      Console.Write(i);
  }
  \end{source}
\end{onlyproblem}
\begin{onlysolution}
  \begin{source}
  1Foo
  \end{source}
\end{onlysolution}
\end{defproblem}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{defproblem}{Linq-Closures}
\begin{onlyproblem}
  Что выведет следующий код?
  \begin{source}
  var actions = new List<Action>();
  foreach (var i in Enumerable.Range(1, 3))
    actions.Add(() => Console.WriteLine(i));
  foreach (var action in actions)
    action();
  \end{source}
\end{onlyproblem}
\begin{onlysolution}
  C\# 1.0 — C\# 4.0: \code{3 3 3}\\
  C\# 5.0+: \code{1 2 3}
\end{onlysolution}
\end{defproblem}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{defproblem}{Linq-Lazy1}
\begin{onlyproblem}
  Что выведет следующий код?
  \begin{source}
  var list = new List<string> {"A", "BB", "CCC"};
  var query = list.Where(c => c.Length == 2);
  list.Remove("BB");
  Console.WriteLine(query.Count());
  \end{source}
\end{onlyproblem}
\begin{onlysolution}
  \begin{source}
  0
  \end{source}
\end{onlysolution}
\end{defproblem}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{defproblem}{Linq-Lazy2}
\begin{onlyproblem}
  Что выведет следующий код?
  \begin{source}
  var list = new List<string> {"A", "BB", "CCC"};
  var minLength = 3;
  var query = list.Where(c => c.Length >= minLength);
  minLength = 2;
  query = query.Where(c => c.Length >= minLength);
  Console.WriteLine(query.Count());
  \end{source}
\end{onlyproblem}
\begin{onlysolution}
  \begin{source}
  2
  \end{source}
\end{onlysolution}
\end{defproblem}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{defproblem}{Linq-Lazy3}
\begin{onlyproblem}
  Что выведет следующий код?
  \begin{source}
  int Inc(int x)
  {
    Console.WriteLine("Inc: " + x);
    return x + 1;
  }
  void Main()
  {
    var numbers = Enumerable.Range(0, 10);
    var query = 
      (from number in numbers
       let number2 = Inc(number)
       where number2 % 2 == 0
       select number2).Take(2);
    foreach (var number in query)
      Console.WriteLine("Number: " + number);
  }
  \end{source}
\end{onlyproblem}
\begin{onlysolution}
  \begin{source}
  Inc: 0
  Inc: 1
  Number: 2
  Inc: 2
  Inc: 3
  Number: 4
  \end{source}
\end{onlysolution}
\end{defproblem}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{defproblem}{Linq-Yield1}
\begin{onlyproblem}
  В какой момент произойдёт \code{Exception}?
  \begin{source}
  public static IEnumerable<int> GetSmallNumbers()
  {
    yield return 1;
    throw new Exception();
    yield return 2;
  }
  void Main()
  {
    var numbers = GetSmallNumbers();
    var evenNumbers = numbers.Select(n => n * 2);
    Console.WriteLine(evenNumbers.FirstOrDefault());
  }
  \end{source}
\end{onlyproblem}
\begin{onlysolution}
  Exception не произойдёт
\end{onlysolution}
\end{defproblem}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{defproblem}{Linq-Yield2}
\begin{onlyproblem}
  В какой момент произойдёт \code{Exception}?
  \begin{source}
  public static IEnumerable<int> GetSmallNumbers()
  {
    throw new Exception();
    yield return 1;
    yield return 2;
  }
  void Main()
  {
    var numbers = GetSmallNumbers();
    var evenNumbers = numbers.Select(n => n * 2);
    Console.WriteLine(evenNumbers.FirstOrDefault());
  }
  \end{source}
\end{onlyproblem}
\begin{onlysolution}
  При вызове \code{evenNumbers.FirstOrDefault()}.
\end{onlysolution}
\end{defproblem}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%